name: Test

on:
  pull_request:
  push:
    branches:
      - master
env:
  CACHE_AFFIX: pnpm-packages
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
  PNPM_VERSION: 8

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install pnpm package manager
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: restore cache for packages if applicable
        uses: actions/cache@v3
        id: packages-cache
        with:
          path: "${{ env.PNPM_CACHE_FOLDER }}"
          key: ${{ runner.os }}-${{ env.CACHE_AFFIX }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.CACHE_AFFIX }}-

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: Testing
        run: |
          pnpm lint
          pnpm t
  smoke:
    name: Smoke Testing
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install pnpm package manager
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: restore cache for packages if applicable
        uses: actions/cache@v3
        id: packages-cache
        with:
          path: "${{ env.PNPM_CACHE_FOLDER }}"
          key: ${{ runner.os }}-${{ env.CACHE_AFFIX }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.CACHE_AFFIX }}-

      - name: install dependencies
        run: |
          pnpm install --frozen-lockfile
          npx playwright install

      - name: Testing
        run: pnpm --filter "@solana/*ui" run ci:test-smoke
