name: Test

on:
  pull_request:
  push:
    branches:
      - master
env:
  CI: true
  PNPM_CACHE_AFFIX: pnpm-packages
  PNPM_CACHE_FOLDER: .pnpm-store
  PNPM_VERSION: 8
  PW_CACHE_AFFIX: playwright
  PW_CACHE_FOLDER: ~/.cache/ms-playwright
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  common:
    name: Common
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install pnpm package manager
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: restore cache for packages if applicable
        uses: actions/cache@v4
        id: packages-cache
        with:
          path: "${{ env.PNPM_CACHE_FOLDER }}"
          key: ${{ runner.os }}-${{ env.PNPM_CACHE_AFFIX }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.PNPM_CACHE_AFFIX }}-

      - name: install dependencies
        run: pnpm i

      - name: testing
        run: |
          pnpm lint
          pnpm t
  # move smoke tests to the separate flow to enable "on" section for them
  smoke:
    name: Smoke
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install pnpm package manager
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: restore cache for packages if applicable
        uses: actions/cache@v4
        id: packages-cache
        with:
          path: "${{ env.PNPM_CACHE_FOLDER }}"
          key: ${{ runner.os }}-${{ env.PNPM_CACHE_AFFIX }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.PNPM_CACHE_AFFIX }}-

      - name: restore playwright cache if applicable
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: "${{ env.PW_CACHE_FOLDER }}"
          key: ${{ runner.os }}-${{ env.PW_CACHE_AFFIX }}-${{ hashFiles('**/.browserslistrc') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.PW_CACHE_AFFIX }}-

      - name: install dependencies
        run: |
          pnpm i
          pnpm exec playwright install --with-deps

      - name: build artefacts
        run: pnpm --filter "@solana/*ui" run build-sb --quiet

      - name: testing
        run: pnpm --filter "@solana/*ui" run ci:test-smoke
